#!/bin/bash

source_url=https://gbdev.io/gb-opcodes/Opcodes.json

add_struct_prop(){
  mode=$3
  struct_prop=$(cat << EOF
,
    .$1 = $2
EOF
)

  if [ $mode == 1 ]; then
    current+=$struct_prop
  elif [ $mode == 2 ]; then
    sp_buf+=$struct_prop
  fi
}

# $1 = the arg string
# $2 = (1 || 2) first or second arg
# $3 = (true || null) immediate (ie. is not a reference)
# $4 = (0 || 1) is branch instruction ("C" is ambiguous between register and condition)
handle_arg(){

  type_key="arg${2}_type"
  val_key="arg${2}_value"
  type_val=""
  val_val=""

  for arg in "$00" "$08" "$10" "$18" "$20" "$28" "$30" "$38"; do
    if [ $arg == $1 ]; then
      type_val="ARG_VEC"
      val_val=${arg/\$/0x}
    fi
  done

  for arg in "A" "B" "C" "D" "E" "H" "L"; do
    if [[ $arg == $1 && $4 == 0 ]]; then
      deref_str=""
      if [ $3 == "null" ]; then
        deref_str="_DEREF"
      fi
      type_val="ARG_R8$deref_str"
      val_val="R8_$arg"
    fi
  done

  for arg in "AF" "BC" "DE" "HL" "SP"; do 
    if [ $arg == $1 ]; then
      deref_str=""
      if [ $3 == "null" ]; then
        deref_str="_DEREF"
      fi
      type_val="ARG_R16$deref_str"
      val_val="R16_$arg"
    fi
  done
  if [ $1 == "NC" ]; then
    type_val="ARG_CC"
    val_val="CC_NC"
  fi;
  if [ $1 == "NZ" ]; then
    type_val="ARG_CC"
    val_val="CC_NZ"
  fi;
  if [ $1 == "Z" ]; then
    type_val="ARG_CC"
    val_val="CC_Z"
  fi;
  if [[ $1 == "C" && $4 == 1 ]]; then
    type_val="ARG_CC"
    val_val="CC_C"
  fi;
  if [ $1 == "a16" ]; then
    type_val="ARG_A16"
    # no val necessary for types parsed from binary directly
  fi;
  if [ $1 == "a8" ]; then
    type_val="ARG_A8"
  fi;
  if [ $1 == "e8" ]; then
    type_val="ARG_E8"
  fi;
  if [ $1 == "n16" ]; then
    type_val="ARG_N16"
  fi;
  if [ $1 == "n8" ]; then
    type_val="ARG_N8"
  fi;
  if [[ "$1" =~ ^[0-7]$ ]]; then
    type_val="ARG_U3"
    val_val=$1
  fi

  if [ "$type_val" != "" ]; then
    add_struct_prop $type_key $type_val 2
    if [ "$val_val" != "" ]; then
      add_struct_prop $val_key $val_val 2
    fi;
  fi;
}

handle_op(){
  op=$1

  # this probably wouldn't work if the json had any strings with spaces
  keyval=(${op//|/ })
  opcode=${keyval[0]}
  opdata=${keyval[1]}

  opname=$(echo $opdata | jq -r '.mnemonic')
  bytes=$(echo $opdata | jq  -r '.bytes')
  cycles=$(echo $opdata | jq  -r '.cycles[0]')
  cycles_noact=$(echo $opdata | jq  -r '.cycles[1]')

  arg1=$(echo $opdata | jq -r '.operands[0].name')
  arg2=$(echo $opdata | jq -r '.operands[1].name')

  is_branch=0
  for brop in "JP" "JR" "CALL" "RET" "RST" "RETI"; do
    if [ $brop == $opname ]; then
      is_branch=1
    fi;
  done

  sp_buf=""
  inc_flag=0
  dec_flag=0
  if [ $arg1 != 'null' ]; then
    immediate=$(echo $opdata | jq -r '.operands[0].immediate')
    increment=$(echo $opdata | jq -r '.operands[0].increment')
    if [ "$increment" != 'null' ]; then
      inc_flag=1
    fi;
    decrement=$(echo $opdata | jq -r '.operands[0].decrement')
    if [ "$decrement" != 'null' ]; then
      dec_flag=1
    fi;
    handle_arg $arg1 1 $immediate $is_branch
  fi

  if [ $arg2 != 'null' ]; then
    immediate=$(echo $opdata | jq -r '.operands[1].immediate')
    increment=$(echo $opdata | jq -r '.operands[1].increment')
    if [ "$increment" != 'null' ]; then
      inc_flag=1
    fi;
    decrement=$(echo $opdata | jq -r '.operands[1].decrement')
    if [ "$decrement" != 'null' ]; then
      dec_flag=1
    fi;
    handle_arg $arg2 2 $immediate $is_branch
  fi

  if [ $inc_flag != 0 ]; then
    opname+="I" # for OP_LDI
  elif [ $dec_flag != 0 ]; then
    opname+="D" # for OP_LDD
  fi

  current=$(cat << EOF
  [$opcode] = { 
    .bytes = $bytes,
    .cycles = $cycles,
    .op = OP_$opname
EOF
)

  if [ $cycles_noact != 'null' ]; then
    struct_prop=""
    add_struct_prop 'cycles_noact' $cycles_noact 1
  fi

  current+=$sp_buf
  current+=$'\n'
  current+='  },'
  current+=$'\n'

  output+=$current
}

# ops=$(jq -r "$jqstr" bb_ops.json)
all_ops=$(curl $source_url)
output=$(cat << EOF
// This file is generated by gen_instructions_meta.sh
// DO NOT CHANGE THIS FILE, instead update the generation script
// Source data: $source_url

#include "instructions_meta.h"

EOF
)


generate_instructions() {
  jqstr=".$1 | keys[] as \$k | \"\(\$k)|\(.[\$k])\""

  ops=$(echo "$all_ops" | jq -r "$jqstr")

  output+=$'\n'
  output+=$'\n'
  output+="const instruction_meta_t $2[256] = {"
  output+=$'\n'

  for op in ${ops[@]};
  do
    handle_op $op
  done

  output+=$'\n'
  output+='};'
}

generate_instructions "unprefixed" "INS_UNPREFIXED"
generate_instructions "cbprefixed" "INS_CBPREFIXED"

echo "$output"
