#!/bin/bash

source_url=https://gbdev.io/gb-opcodes/Opcodes.json

output=$(cat << EOF
// This file is generated by gen_instructions_meta.sh
// Source data: $source_url
#include "instructions_meta.h"

const instruction_meta_t INSTRUCTIONS[256] = {

EOF
)

add_struct_prop(){
  output+=$(cat << EOF
,
    .$1 = $2
EOF
)
}

jqstr='.unprefixed | keys[] as $k | "\($k)|\(.[$k])"'
ops=$(jq -r "$jqstr" bb_ops.json)
# ops=$(curl $source_url | jq -r "$jqstr")

for op in ${ops[@]};
do
  # this probably wouldn't work if the json had any strings with spaces
  keyval=(${op//|/ })
  opcode=${keyval[0]}
  opdata=${keyval[1]}

  opname=$(echo $opdata | jq -r '.mnemonic')
  bytes=$(echo $opdata | jq  -r '.bytes')
  cycles=$(echo $opdata | jq  -r '.cycles[0]')
  cycles_noact=$(echo $opdata | jq  -r '.cycles[1]')

  arg1=$(echo $opdata | jq -r '.operands[0].name')
  arg2=$(echo $opdata | jq -r '.operands[1].name')

  output+=$(cat << EOF
  [$opcode] = { 
    .bytes = $bytes,
    .cycles = $cycles,
    .op = OP_$opname
EOF
)

  if [ $cycles_noact != 'null' ]; then
    add_struct_prop 'cycles_noact' $cycles_noact
  fi

  if [ $arg1 != 'null' ]; then
    # todo handle value and type name transformation
    add_struct_prop 'arg1_type' $arg1
  fi

  # todo everything else 

done

output+=$'\n'
output+='};'
echo "$output"
