// This file is generated by gen_instructions_meta.sh
// DO NOT CHANGE THIS FILE, instead update the generation script
// Source data: https://gbdev.io/gb-opcodes/Opcodes.json

#include "instructions_meta.h"

const instruction_meta_t INS_UNPREFIXED[256] = {
  [0x00] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_NOP
  },
  [0x01] = { 
    .bytes = 3,
    .cycles = 12,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC,
    .arg2_type = ARG_N16
  },
  [0x02] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x03] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_INC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC
  },
  [0x04] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x05] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x06] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_N8
  },
  [0x07] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_RLCA
  },
  [0x08] = { 
    .bytes = 3,
    .cycles = 20,
    .op = OP_LD,
    .arg1_type = ARG_A16,
    .arg2_type = ARG_R16,
    .arg2_value = R16_SP
  },
  [0x09] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R16,
    .arg2_value = R16_BC
  },
  [0x0A] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_BC
  },
  [0x0B] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_DEC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC
  },
  [0x0C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x0D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x0E] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_N8
  },
  [0x0F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_RRCA
  },
  [0x10] = { 
    .bytes = 2,
    .cycles = 4,
    .op = OP_STOP,
    .arg1_type = ARG_N8
  },
  [0x11] = { 
    .bytes = 3,
    .cycles = 12,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE,
    .arg2_type = ARG_N16
  },
  [0x12] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x13] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_INC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE
  },
  [0x14] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x15] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x16] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_N8
  },
  [0x17] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_RLA
  },
  [0x18] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_JR,
    .arg1_type = ARG_E8
  },
  [0x19] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R16,
    .arg2_value = R16_DE
  },
  [0x1A] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_DE
  },
  [0x1B] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_DEC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE
  },
  [0x1C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x1D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x1E] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_N8
  },
  [0x1F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_RRA
  },
  [0x20] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_JR,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NZ,
    .arg2_type = ARG_E8
  },
  [0x21] = { 
    .bytes = 3,
    .cycles = 12,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_N16
  },
  [0x22] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDI,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x23] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_INC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x24] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x25] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x26] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_N8
  },
  [0x27] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DAA
  },
  [0x28] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_JR,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_Z,
    .arg2_type = ARG_E8
  },
  [0x29] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x2A] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDI,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x2B] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_DEC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x2C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x2D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x2E] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_N8
  },
  [0x2F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CPL
  },
  [0x30] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_JR,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NC,
    .arg2_type = ARG_E8
  },
  [0x31] = { 
    .bytes = 3,
    .cycles = 12,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_SP,
    .arg2_type = ARG_N16
  },
  [0x32] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x33] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_INC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_SP
  },
  [0x34] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_INC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x35] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_DEC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x36] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_N8
  },
  [0x37] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SCF
  },
  [0x38] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_JR,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_C,
    .arg2_type = ARG_E8
  },
  [0x39] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R16,
    .arg2_value = R16_SP
  },
  [0x3A] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x3B] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_DEC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_SP
  },
  [0x3C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_INC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x3D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DEC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x3E] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0x3F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CCF
  },
  [0x40] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x41] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x42] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x43] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x44] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x45] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x46] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x47] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x48] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x49] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x4A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x4B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x4C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x4D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x4E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x4F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x50] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x51] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x52] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x53] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x54] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x55] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x56] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x57] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x58] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x59] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x5A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x5B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x5C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x5D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x5E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x5F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x60] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x61] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x62] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x63] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x64] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x65] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x66] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x67] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x68] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x69] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x6A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x6B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x6C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x6D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x6E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x6F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x70] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x71] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x72] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x73] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x74] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x75] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x76] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_HALT
  },
  [0x77] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x78] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x79] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x7A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x7B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x7C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x7D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x7E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x7F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x80] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x81] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x82] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x83] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x84] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x85] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x86] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x87] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x88] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x89] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x8A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x8B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x8C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x8D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x8E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x8F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x90] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x91] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x92] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x93] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x94] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x95] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x96] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x97] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x98] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x99] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x9A] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x9B] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x9C] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x9D] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x9E] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x9F] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xA0] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xA1] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xA2] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xA3] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xA4] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xA5] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xA6] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xA7] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xA8] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xA9] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xAA] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xAB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xAC] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xAD] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xAE] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xAF] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xB0] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xB1] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xB2] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xB3] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xB4] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xB5] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xB6] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xB7] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xB8] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xB9] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xBA] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xBB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xBC] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xBD] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xBE] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xBF] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xC0] = { 
    .bytes = 1,
    .cycles = 20,
    .op = OP_RET,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NZ
  },
  [0xC1] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_POP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC
  },
  [0xC2] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_JP,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NZ,
    .arg2_type = ARG_A16
  },
  [0xC3] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_JP,
    .arg1_type = ARG_A16
  },
  [0xC4] = { 
    .bytes = 3,
    .cycles = 24,
    .op = OP_CALL,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NZ,
    .arg2_type = ARG_A16
  },
  [0xC5] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_PUSH,
    .arg1_type = ARG_R16,
    .arg1_value = R16_BC
  },
  [0xC6] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_ADD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xC7] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xC8] = { 
    .bytes = 1,
    .cycles = 20,
    .op = OP_RET,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_Z
  },
  [0xC9] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RET
  },
  [0xCA] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_JP,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_Z,
    .arg2_type = ARG_A16
  },
  [0xCB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_PREFIX
  },
  [0xCC] = { 
    .bytes = 3,
    .cycles = 24,
    .op = OP_CALL,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_Z,
    .arg2_type = ARG_A16
  },
  [0xCD] = { 
    .bytes = 3,
    .cycles = 24,
    .op = OP_CALL,
    .arg1_type = ARG_A16
  },
  [0xCE] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_ADC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xCF] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xD0] = { 
    .bytes = 1,
    .cycles = 20,
    .op = OP_RET,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NC
  },
  [0xD1] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_POP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE
  },
  [0xD2] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_JP,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NC,
    .arg2_type = ARG_A16
  },
  [0xD3] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_D3
  },
  [0xD4] = { 
    .bytes = 3,
    .cycles = 24,
    .op = OP_CALL,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_NC,
    .arg2_type = ARG_A16
  },
  [0xD5] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_PUSH,
    .arg1_type = ARG_R16,
    .arg1_value = R16_DE
  },
  [0xD6] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SUB,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xD7] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xD8] = { 
    .bytes = 1,
    .cycles = 20,
    .op = OP_RET,
    .cycles_noact = 8,
    .arg1_type = ARG_CC,
    .arg1_value = CC_C
  },
  [0xD9] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RETI
  },
  [0xDA] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_JP,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_C,
    .arg2_type = ARG_A16
  },
  [0xDB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_DB
  },
  [0xDC] = { 
    .bytes = 3,
    .cycles = 24,
    .op = OP_CALL,
    .cycles_noact = 12,
    .arg1_type = ARG_CC,
    .arg1_value = CC_C,
    .arg2_type = ARG_A16
  },
  [0xDD] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_DD
  },
  [0xDE] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SBC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xDF] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xE0] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_LDH,
    .arg1_type = ARG_A8,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xE1] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_POP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0xE2] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDH,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xE3] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_E3
  },
  [0xE4] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_E4
  },
  [0xE5] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_PUSH,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0xE6] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_AND,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xE7] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xE8] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_ADD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_SP,
    .arg2_type = ARG_E8
  },
  [0xE9] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_JP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0xEA] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_LD,
    .arg1_type = ARG_A16,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xEB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_EB
  },
  [0xEC] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_EC
  },
  [0xED] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_ED
  },
  [0xEE] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_XOR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xEF] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xF0] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_LDH,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_A8
  },
  [0xF1] = { 
    .bytes = 1,
    .cycles = 12,
    .op = OP_POP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_AF
  },
  [0xF2] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LDH,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xF3] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_DI
  },
  [0xF4] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_F4
  },
  [0xF5] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_PUSH,
    .arg1_type = ARG_R16,
    .arg1_value = R16_AF
  },
  [0xF6] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_OR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xF7] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },
  [0xF8] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_LDI,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL,
    .arg2_type = ARG_R16,
    .arg2_value = R16_SP
  },
  [0xF9] = { 
    .bytes = 1,
    .cycles = 8,
    .op = OP_LD,
    .arg1_type = ARG_R16,
    .arg1_value = R16_SP,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xFA] = { 
    .bytes = 3,
    .cycles = 16,
    .op = OP_LD,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_A16
  },
  [0xFB] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_EI
  },
  [0xFC] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_FC
  },
  [0xFD] = { 
    .bytes = 1,
    .cycles = 4,
    .op = OP_ILLEGAL_FD
  },
  [0xFE] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_CP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A,
    .arg2_type = ARG_N8
  },
  [0xFF] = { 
    .bytes = 1,
    .cycles = 16,
    .op = OP_RST
  },

};

const instruction_meta_t INS_CBPREFIXED[256] = {
  [0x00] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x01] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x02] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x03] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x04] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x05] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x06] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RLC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x07] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RLC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x08] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x09] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x0A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x0B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x0C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x0D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x0E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RRC,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x0F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RRC,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x10] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x11] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x12] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x13] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x14] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x15] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x16] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RL,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x17] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x18] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x19] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x1A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x1B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x1C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x1D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x1E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RR,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x1F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RR,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x20] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x21] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x22] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x23] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x24] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x25] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x26] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SLA,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x27] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SLA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x28] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x29] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x2A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x2B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x2C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x2D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x2E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SRA,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x2F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRA,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x30] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x31] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x32] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x33] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x34] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x35] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x36] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SWAP,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x37] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SWAP,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x38] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_B
  },
  [0x39] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_C
  },
  [0x3A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_D
  },
  [0x3B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_E
  },
  [0x3C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_H
  },
  [0x3D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_L
  },
  [0x3E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SRL,
    .arg1_type = ARG_R16,
    .arg1_value = R16_HL
  },
  [0x3F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SRL,
    .arg1_type = ARG_R8,
    .arg1_value = R8_A
  },
  [0x40] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x41] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x42] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x43] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x44] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x45] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x46] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x47] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x48] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x49] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x4A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x4B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x4C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x4D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x4E] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x4F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x50] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x51] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x52] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x53] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x54] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x55] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x56] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x57] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x58] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x59] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x5A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x5B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x5C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x5D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x5E] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x5F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x60] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x61] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x62] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x63] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x64] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x65] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x66] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x67] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x68] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x69] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x6A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x6B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x6C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x6D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x6E] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x6F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x70] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x71] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x72] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x73] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x74] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x75] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x76] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x77] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x78] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x79] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x7A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x7B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x7C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x7D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x7E] = { 
    .bytes = 2,
    .cycles = 12,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x7F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_BIT,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x80] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x81] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x82] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x83] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x84] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x85] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x86] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x87] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x88] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x89] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x8A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x8B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x8C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x8D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x8E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x8F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x90] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x91] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x92] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x93] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x94] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x95] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x96] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x97] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0x98] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0x99] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0x9A] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0x9B] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0x9C] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0x9D] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0x9E] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0x9F] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xA0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xA1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xA2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xA3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xA4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xA5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xA6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xA7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xA8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xA9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xAA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xAB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xAC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xAD] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xAE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xAF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xB0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xB1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xB2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xB3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xB4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xB5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xB6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xB7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xB8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xB9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xBA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xBB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xBC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xBD] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xBE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xBF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_RES,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xC0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xC1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xC2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xC3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xC4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xC5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xC6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xC7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 0,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xC8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xC9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xCA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xCB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xCC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xCD] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xCE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xCF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 1,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xD0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xD1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xD2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xD3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xD4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xD5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xD6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xD7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 2,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xD8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xD9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xDA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xDB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xDC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xDD] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xDE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xDF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 3,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xE0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xE1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xE2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xE3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xE4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xE5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xE6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xE7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 4,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xE8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xE9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xEA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xEB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xEC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xED] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xEE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xEF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 5,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xF0] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xF1] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xF2] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xF3] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xF4] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xF5] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xF6] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xF7] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 6,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },
  [0xF8] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_B
  },
  [0xF9] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_C
  },
  [0xFA] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_D
  },
  [0xFB] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_E
  },
  [0xFC] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_H
  },
  [0xFD] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_L
  },
  [0xFE] = { 
    .bytes = 2,
    .cycles = 16,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R16,
    .arg2_value = R16_HL
  },
  [0xFF] = { 
    .bytes = 2,
    .cycles = 8,
    .op = OP_SET,
    .arg1_type = ARG_U3,
    .arg1_value = 7,
    .arg2_type = ARG_R8,
    .arg2_value = R8_A
  },

};
